### ISSUE TITLE
"TapeType" in "AD_real" does not name a type

### ISSUE THREAD

**Issue by if362005** [LLNL/adapt-fp#4]
When I run the demo, the compiler reports an error as in the question. The problem is shown in the screenshot
![1](https://user-images.githubusercontent.com/54499718/172130265-f8c38750-4f5a-467a-82ba-b34ecb2aeb10.png)

**Comment by lam2mo** [comment]
I believe this was fixed by #714bd41a3313641b051e3cc21b47a752c44c048a.

**Comment by if362005** [comment]
> 
Thanks a lot！
